apiVersion: v1
kind: Pod
metadata:
  name: example
  namespace: default
  labels:
    app: example
spec:
  nodeSelector:
    role: web
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent

