apiVersion: v1
kind: Pod
metadata:
  name: example
  namespace: default
  labels:
    app: example
    role: web
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent

