apiVersion: v1
kind: Pod
metadata:
  name: example
  namespace: default
  labels:
    app: example
spec:
  containers:
  - name: nginx
    image: nginx:1.15.12
    resources:
      limits:
        cpu: 500m
        memory: 0.5Gi
      requests:
        cpu: 0
        memory: 0.5Gi

