apiVersion: v1
kind: Pod
metadata:
  name: projected-volume
spec:
  containers:
  - name: secret-volume
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: cred
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: cred
    projected:
      sources:
      - secret:
          name: user
      - secret:
          name: pass
