apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-ceph-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: block
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
