apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-test
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: jaeger-test
  template:
    metadata:
      labels:
        app: jaeger-test
    spec:
      containers:
      - name: hotrod
        image: jaegertracing/example-hotrod:latest
        env:
        - name: JAEGER_AGENT_HOST
          value: "localhost"
        - name: JAEGER_AGENT_PORT
          value: "6831"

