apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  ingress:
    enabled: false
  query:
    replicas: 2
  collector:
    replicas: 3
  storage:
    type: elasticsearch
    dependencies:
      enabled: false
    options:
      es:
        server-urls: http://elasticsearch-master:9200
        index-prefix: tracing

