apiVersion: v1
kind: limitRange
metadata:
  name: limits-ns-test
  namespace: test
spec:
  limits:
  - max:
      cpu: 2
      memory: 4Gi
    min:
      cpu: 100m
      memory: 100Mi
    maxLimitRequestRatio:
      cpu: 4
      memory: 4
    type: Pod
  - default: #在没有配置的情况下，使用默认配置
      cpu: 200m
      memory: 500Mi
    defaultRequest:
      cpu: 100m
      memory: 200Mi
    min:
      cpu: 100m
      memory: 100Mi
    max:
      cpu: 2
      memory: 2Gi
    maxLimitRequestRatio:
      cpu: 4
      memory: 4
    type: Container
