apiVersion: v1
kind: Pod
metadata:
  name: with-required-nodeaffinity-1
spec:
  affinity:
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - {key: zone, operator: In, values: ["foo"]}
  containers:
  - name: myapp
    image: chenkaidi/myapp:v1
